
-- Create semester_majors junction table
CREATE TABLE IF NOT EXISTS public.semester_majors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_id BIGINT REFERENCES public.semesters(id) ON DELETE CASCADE,
    major_id BIGINT REFERENCES public.majors(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(semester_id, major_id)
);

-- Enable Row Level Security
ALTER TABLE public.semester_majors ENABLE ROW LEVEL SECURITY;

-- Create policies (allowing all operations for now to match typical development setup)
-- In a production environment, you should restrict this to authenticated users or specific roles.
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'semester_majors' AND policyname = 'Public Access'
    ) THEN
        CREATE POLICY "Public Access" ON public.semester_majors FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- Verify other tables just in case
-- CREATE TABLE IF NOT EXISTS public.semesters (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
-- CREATE TABLE IF NOT EXISTS public.majors (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
-- CREATE TABLE IF NOT EXISTS public.major_subjects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, major_id BIGINT REFERENCES public.majors(id) ON DELETE CASCADE, subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE, created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(major_id, subject_id));
